apiVersion: v1
kind: ConfigMap
metadata:
  name: oxpassport-cm
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  DOMAIN: {{GLUU_DOMAIN}}
  GLUU_LDAP_URL: "opendj:1636"
  GLUU_MAX_RAM_FRACTION: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: oxpassport
  labels:
    app: oxpassport
spec:
  ports:
  - port: 8090
    name: oxpassport
  selector:
    app: oxpassport
  # type: NodePort
  # clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxpassport
  labels:
    app: oxpassport
spec:
  # serviceName: oxpassport
  replicas: 1
  selector:
    matchLabels:
      app: oxpassport
  template:
    metadata:
      labels:
        app: oxpassport
    spec:
      containers:
      - name: oxpassport
        imagePullPolicy: Always
        image: eoepca/oxpassport:4.1.1_01
        ports:
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: oxpassport-cm
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - {{GLUU_DOMAIN}}
