sudo: required
language: java
install: true

services:
  - docker

jobs:
  include:
    - stage: test
      branch:
        only:
        - develop
      # Minikube installation taken from: https://github.com/LiliC/travis-minikube/blob/minikube-30-kube-1.12/.travis.yml
      # We need the systemd for the kubeadm and it's default from 16.04+
      dist: xenial
      #before_script: cd travis && sh setupCluster.sh
      #script: cd terraform/test && terraform init -input=false
      script: cd travis && sh setupCluster.sh

      after_success:
        - cd ./tests/acceptance/UserManagement/LoginService
        - robot ./LoginService.robot
      # deploy:
        # - provider: script
          # skip_cleanup: true
          # script: sh ${TRAVIS_BUILD_DIR}/travis/test_login-buildingblock.sh
          # on:
            # branch: develop

import:
  - docs/.travis.yml



#notifications:
#  slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
#  email:
#    recipients:
#      - a.person@acme.com
#      - a.n.other@acme.com
#    on_success: never # default: change
#    on_failure: never # default: always