# Declare variables to be passed into your templates.

replicaCount: 1
dynamicStorage: true

image:
  repository: oxauth
  tag: 4.1.1_03
  pullPolicy: Always

# VolumeClaim values
volumeClaim:
  storage: 50M

#ConfigMap values
gluuLdapUrl: opendj:1636
gluuMaxRamFraction: 1

#Resources for the deployment
requests:
  memory: 128Mi
limits:
  memory: 128Mi

#hostAliases
nginxIP: 192.168.99.100

#ports for the deployment
ports:
  containerPort: 8080

# livenessProbe
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30

# readinessProbe
readinessProbe:
  initialDelaySeconds: 25
  periodSeconds: 25

#VolumeMounts
volumeMounts:
  logs:
    mountPath: /opt/gluu/jetty/oxauth/logs
    name: eoepca-userman-pv-host
    sub_path: oxauth/logs
  ext:
    mountPath: /opt/gluu/jetty/oxauth/lib/ext
    name: eoepca-userman-pv-host
    sub_path: oxauth/lib/ext
  static:
    mountPath: /opt/gluu/jetty/oxauth/custom/static
    name: eoepca-userman-pv-host
    sub_path: oxauth/custom/static
  pages:
    mountPath: /opt/gluu/jetty/oxauth/custom/pages
    name: eoepca-userman-pv-host
    sub_path: oxauth/custom/pages