# Default values for login-service.

global:
  namespace: default
  serviceName: opendj
  nginxIp: 10.0.2.15
  oxAuthServiceName: oxauth
  persistenceServiceName: persistence
  oxTrustSeriveName: oxtrust
  domain: demoexample.gluu.org
  gluuLdapUrl: opendj:1636
  gluuMaxRamFraction: 1
  configAdapterName: kubernetes
  configSecretAdapter: kubernetes
  provisioner: k8s.io/minikube-hostpath
  pool: default
  gcePdStorageType: pd-standard
  description: gluu-config-init-volume
  fsType: ext4
  
persistence: 
  accessModes: ReadWriteMany
  dbStorageSize: 5Gi
  type: DirectoryOrCreate

config:
  # Required environment variables for generating Gluu server initial config
  enabled: true
  # ldapType only OpenDJ is supported
  ldapType: opendj
  # domain name where the Gluu Server resides
  domain: demoexample.gluu.org
  # organisation location details
  countryCode: ES
  state: Madrid
  city: Tres Cantos
  adminPass: admin_Abcd1234#
  ldapPass: admin_Abcd1234#
  email: eoepca@deimos-space.com
  orgName: Deimos Space S.L.U.
  gluuConfAdapter: kubernetes
  ldapType: opendj
  redisPass: aaaa
  pdpEp: /pdp
  # VolumeClaim values
  volumeClaim:
    name: um-login-service-config-pvc

  image: eoepca/config-init:4.1.1_02

opendj:
  enabled: true
  # options REDIS/NATIVE_PERSISTENCE
  gluuCacheType: NATIVE_PERSISTENCE
  # options true/false : must be enabled if cache type is REDIS
  gluuRedisEnabled: false
  #opendj docker image and policy
  imagePullPolicy: Always
  image: eoepca/wrends:4.1.1_01
  persistence:
    #persistence docker image and policy
    imagePullPolicy: Always
    image: eoepca/um-login-persistence:v1.1.1
    #COIH Client ID and Secret for passport login
    coihClientIDv: ""
    coihClientSecretv: ""
    umaResourceLifetime: UMA_RESOURCE_LIFETIME
    umaResourceLifetimev: 2147483647
  # VolumeClaim values
  volumeClaim:
    name: um-login-service-opendj-pvc
  readinessProbe:
    initialDelaySeconds: 150
    periodSeconds: 90
  livenessProbe:
    initialDelaySeconds: 150
    periodSeconds: 90

oxpassport:
  enabled: true
  image:
    repository: eoepca/um-login-passport
    tag: v0.1.1
    # tag: 4.0.1_03
    pullPolicy: Always

oxauth:
  enabled: true
  dynamicStorage: true
  image:
    # repository eoepca/oxauth:4.1.1_03
    repository: oxauth
    tag: 4.1.1_03
    pullPolicy: Always
  volumeClaim:
    name: um-login-service-oxauth-pvc
  livenessProbe:
    initialDelaySeconds: 100
    periodSeconds: 60
  readinessProbe:
    initialDelaySeconds: 100
    periodSeconds: 60

oxtrust:
  enabled: true
  #RAM fraction, defaults a 100%
  gluuMaxRamFraction: 1
  dynamicStorage: true
  image:
    # repository eoepca/oxtrust:4.1.1_02
    repository: oxtrust
    tag: 4.1.1_02
    pullPolicy: Always
  volumeClaim:
    name: um-login-service-oxtrust-pvc
  livenessProbe:
    initialDelaySeconds: 100
    periodSeconds: 60
  readinessProbe:
    initialDelaySeconds: 100
    periodSeconds: 60

nginx:
  image:
    repository: kungus/gluu-tls-initializer
    tag: stable
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - demoexample.gluu.org
    tls: 
    - secretName: gluu-tls-certificate
      hosts:
        - demoexample.gluu.org
  resources: {}
