apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  GLUU_SECRET_ADAPTER: "{{GLUU_SECRET_ADAPTER}}"
  ADMIN_PW: "{{ADMIN_PW}}"
  EMAIL: "{{EMAIL}}"
  DOMAIN: "{{DOMAIN}}"
  ORG_NAME: "{{ORG_NAME}}"
  COUNTRY_CODE: "{{COUNTRY_CODE}}"
  STATE: "{{STATE}}"
  CITY: "{{CITY}}"
  GLUU_CONFIG_ADAPTER: "{{GLUU_CONFIG_ADAPTER}}"
  LDAP_TYPE: "{{LDAP_TYPE}}"
  
---

apiVersion: batch/v1
kind: Job
metadata:
  name: config-init
spec:
  template:
    metadata:
      labels:
        app: config-init
    spec:
      restartPolicy: Never
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-volume-claim
      containers:
        - name: config-init
          image: gluufederation/config-init:3.1.6_03
          volumeMounts:
            - mountPath: /opt/config-init/db
              name: config
              subPath: db
          envFrom:
          - configMapRef:
              name: config-cm
          args: ["generate", "--admin-pw", "$(ADMIN_PW)", "--email", "$(EMAIL)", "--domain", "$(DOMAIN)", "--org-name", "$(ORG_NAME)", "--country-code", "$(COUNTRY_CODE)", "--state", "$(STATE)", "--city", "$(CITY)", "--ldap-type", "$(LDAP_TYPE)"]
