apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.name" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}