apiVersion: v1
kind: ConfigMap
metadata:
  name: oxauth-cm
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  DOMAIN: "demoexample.gluu.org"
  GLUU_SYNC_CASA_MANIFESTS: "false"
  GLUU_LDAP_URL: "opendj:1636"
  GLUU_MAX_RAM_FRACTION: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: oxauth
  labels:
    app: oxauth
spec:
  ports:
  - port: 8080
    name: oxauth
  selector:
    app: oxauth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxauth
  labels:
    app: oxauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxauth
  template:
    metadata:
      labels:
        app: oxauth
    spec:
      containers:
      - name: oxauth
        imagePullPolicy: Always
        image: gluufederation/oxauth:4.1.1_03
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: oxauth-cm
        volumeMounts:
          - mountPath: /opt/gluu/jetty/oxauth/logs
            name: oxauth-logs
          - mountPath: /opt/gluu/jetty/oxauth/lib/ext
            name: oxauth-lib-ext
          - mountPath: /opt/gluu/jetty/oxauth/custom/static
            name: oxauth-custom-static
          - mountPath: /opt/gluu/jetty/oxauth/custom/pages
            name: oxauth-custom-pages       
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - demoexample.gluu.org
      volumes:
      - name: oxauth-logs
        persistentVolumeClaim:
          claimName: oxauth-logs-volume-claim
      - name: oxauth-lib-ext
        persistentVolumeClaim:
          claimName: oxauth-lib-ext-volume-claim
      - name: oxauth-custom-static
        persistentVolumeClaim:
          claimName: oxauth-custom-static-volume-claim
      - name: oxauth-custom-pages
        persistentVolumeClaim:
          claimName: oxauth-custom-pages-volume-claim
