apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "oxauth.fullname" . }}
  labels:
    app: {{ .Values.global.oxAuthServiceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.oxAuthServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.oxAuthServiceName }}
    spec:
      containers:
      - name: {{ template "login-service.fullname" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: eoepca/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.requests.memory }}
            cpu: {{ .Values.requests.cpu }}
          # limits:
          #   memory: {{ .Values.limits.memory }} 
        # {{ if .Files.Get "custom/customizations.tar.gz" }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "if [ -f /data/customizations_oxauth.tar.gz ]; then tar xvf /data/customizations_oxauth.tar.gz -C /opt/gluu/jetty/oxauth/; fi"]

              #command: ["/bin/sh", "-c", "if [ -f /data/customizations.tar.gz ]; then cd /data/ && tar -xvf customizations.tar.gz -C /opt/gluu/jetty/oxauth/custom/; fi"]
              #command: ["/bin/sh", "-c", "mkdir -p /opt/gluu/jetty/oxauth/custom/pages/ && cp /data/*.xhtml /opt/gluu/jetty/oxauth/custom/pages && mkdir -p /opt/gluu/jetty/oxauth/custom/static/css/ && cp /data/*.css /opt/gluu/jetty/oxauth/custom/static/css/ && mkdir -p /opt/gluu/jetty/oxauth/custom/static/img/ && cp /data/*.png /opt/gluu/jetty/oxauth/custom/static/img/ && mkdir -p /opt/gluu/jetty/oxauth/custom/static/js/ && cp /data/*.js /opt/gluu/jetty/oxauth/custom/static/js/"]
        # {{ end }}
        ports:
        - name: oxauth
          containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ template "oxauth.fullname" . }}-cm
        volumeMounts:
        {{- range $key, $value := .Values.volumeMounts }}
          - mountPath: {{ $value.mountPath }}
            name: vol-userman
            subPath: {{ $value.subPath }}
        {{- end }}
          - name: customizations
            mountPath: /data/
        livenessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: {{ .Values.ports.containerPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        readinessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: {{ .Values.ports.containerPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      volumes:
        - name: vol-userman
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}
        - name: customizations
          configMap:
            name: front-customizations
