apiVersion: batch/v1
kind: Job
metadata:
  name: um-login-persistence
spec:
  template:
    spec:
      containers:
      - name: um-login-persistence
        image: eoepca/um-login-persistence:latest
        imagePullPolicy: Always
        env:
            - name: GLUU_CONFIG_ADAPTER
              value: "kubernetes"
            - name: GLUU_SECRET_ADAPTER
              value: "kubernetes"
            - name: GLUU_PASSPORT_ENABLED
              value: "true"
            - name: GLUU_LDAP_URL
              value: "opendj:1636"
            - name: GLUU_PERSISTENCE_TYPE
              value: "ldap"
            - name: GLUU_OXTRUST_CONFIG_GENERATION
              value: "false"
            - name: GLUU_CACHE_TYPE
              value: "NATIVE_PERSISTENCE"
            - name: LP_CLIENT_ID
              value: "59f1fed27153f631bc08"
            - name: LP_CLIENT_SECRET
              value: "640baffac0948454c48de2505726f53d11adc8a6"
            - name: COIH_CLIENT_ID
              value: ""
            - name: COIH_CLIENT_SECRET
              value: ""
      restartPolicy: Never
  backoffLimit: 1
