apiVersion: v1
kind: PersistentVolume
metadata:
  name: eoepca-userman-pv-host
  labels:
    eoepca_type: userman
spec:
  capacity:
    storage: {{ .Values.persistence.dbStorageSize }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  hostPath:
    path: "/kubedata/userman"
    type: {{ .Values.persistence.type }}

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: eoepca-userman-pv
  labels:
    eoepca_type: userman
spec:
  storageClassName: eoepca-nfs
  accessModes:
    - {{ .Values.persistence.accessModes }}
  capacity:
    storage: {{ .Values.persistence.dbStorageSize }}
  hostPath:
    path: "/data/userman"
    type: {{ .Values.persistence.type }}
