apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eoepca-userman-pvc
  labels:
    eoepca_type: userman
spec:
  accessModes:
    - {{ .Values.persistence.accessModes }}
  capacity:
    storage: {{ .Values.persistence.dbStorageSize }}
  resources:
    requests:
      storage: {{ .Values.persistence.dbStorageSize }}
  selector:
    matchLabels:
      eoepca_type: userman
